### ISSUE TITLE
GraphAware Natural Language Processing

### ISSUE THREAD

**Issue by shalaka92** [graphaware/neo4j-nlp#102]
I am using Neo4j 3.4.1 version on Linux desktop. 
My java version are:
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

I installed the latest versions of Graphaware nlp plugins in my plugin folder and gave the permissions in neo4j.conf file as follows -

dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware
com.graphaware.runtime.enabled=true
com.graphaware.module.NLP.1=com.graphaware.nlp.module.NLPBootstrapper
dbms.security.procedures.whitelist=ga.nlp.*

It gives me following error -  Database failed to start: DB [database-5153bcb3-327c-480a-951c-70b5192d1b96] 'v3.4.1' exited with status 'KILLED'. Check the logs

Logs shows me - 

![logs](https://user-images.githubusercontent.com/35445380/42446596-812a369e-8394-11e8-9761-4a1b530a936a.png)
![logs1](https://user-images.githubusercontent.com/35445380/42446598-8151a6ca-8394-11e8-95ee-417601278138.png)
![logs2](https://user-images.githubusercontent.com/35445380/42446599-817b2202-8394-11e8-8f38-aeb37175b58d.png)
![plugins_folder](https://user-images.githubusercontent.com/35445380/42446600-81a83f58-8394-11e8-9247-e0914d00a31a.png)

**Comment by ikwattro** [comment]
HI @shalaka92 

1. You need to use only one jar of the `graphaware-server`, community or enterprise, not both

2. Please upgrade to 3.4.0.52.11 for stanford-nlp, it contains the fix of the exception you can see : 

https://products.graphaware.com/download/nlp-stanford-nlp/nlp-stanfordnlp-3.4.0.52.11.jar

**Comment by shalaka92** [comment]
I did the above 2 steps, but still its giving me the following error in the neo4j browser - 
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `ga.nlp.annotate`: Caused by: java.lang.RuntimeException: A pipeline should be given or set as default

**Comment by ikwattro** [comment]
It is not an error, it means that the plugin is working and that you are ready to read the documentation in the README about the steps to do before annotating. Enjoy !

https://github.com/graphaware/neo4j-nlp#getting-started

**Comment by shalaka92** [comment]
Its working. Thanks a lot.
