### ISSUE TITLE
Graphaware/neo4j-nlp

### ISSUE THREAD

**Issue by shalaka92** [graphaware/neo4j-nlp#108]
I am using Neo4j 3.4.1 version on Ubuntu 16.04 LTS desktop.
Memory is 7.7 GiB
My java version are:
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

I installed Graphaware nlp plugin. 
I tried running CALL ga.nlp.annotate({text: n.text, id: id(n), pipeline:'customNER3'}) after creating a pipeline named customNER3. 

It gives me the following error - 
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `ga.nlp.annotate`: Caused by: java.lang.OutOfMemoryError: Java heap space.

I tried to increase the heap space by changing in the settings of neo conf file as follows-
dbms.memory.heap.initial_size=1G 
dbms.memory.heap.max_size=1G
 or 
dbms.memory.heap.initial_size=2G
dbms.memory.heap.max_size=2G

It gives me the following error - 
Database failed to start: Startup timed out, see logs.. Check the logs
I have attached the logs - 

![logs0](https://user-images.githubusercontent.com/35445380/43392385-258c55dc-9411-11e8-8432-5c8c481a40e6.png)
![logs1](https://user-images.githubusercontent.com/35445380/43392386-25ca509e-9411-11e8-8fed-c6b3465ea1e0.png)
![logs2](https://user-images.githubusercontent.com/35445380/43392387-26072780-9411-11e8-837a-dedb10a484e3.png)
![logs3](https://user-images.githubusercontent.com/35445380/43392388-2641f46e-9411-11e8-90e1-885b323c215d.png)

**Comment by ikwattro** [comment]
2GB is a bit low, increase to 4 or 6

**Comment by shalaka92** [comment]
Its working now. Thanks.
I created a pipeline as follows -
CALL ga.nlp.processor.addPipeline({name: 'customNER3', textProcessor: 'com.graphaware.nlp.processor.stanford.StanfordTextProcessor', processingSteps: {tokenize: true, ner: true, sentiment: true, dependency: true}})

I was trying to run the sentiment analysis as follows -
MATCH (t:Tweet)-[]-(a:AnnotatedText) 
CALL ga.nlp.sentiment(a) YIELD result 
RETURN result;

It gives me an error -
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `ga.nlp.sentiment`: Caused by: java.lang.RuntimeException: Pipeline: sentiment doesn't exist

And for enrich concept it gives me this error-
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `ga.nlp.enrich.concept`: Caused by: java.lang.RuntimeException: A pipeline should be given or set as default

**Comment by ikwattro** [comment]
Great

1. Your pipeline is called `customNER3`, not `sentiment`, adjust your call to reflect this, that said you will already have the sentiment on the sentences as the pipeline has it by default, check the labels of your Sentence nodes.

2. Add a `pipeline: 'customNER3` in your call for enrich, or just set your created pipeline as default : 

```
CALL ga.nlp.processor.pipeline.default('customNER3')
```
