### ISSUE TITLE
Compatibility with German Text Data

### ISSUE THREAD

**Issue by eayan** [graphaware/neo4j-nlp#118]
Hi,

I was wondering if Neo4j is compatible with German texts, I mean is it possible to tokenize German textx via pos tagger as in English texts?
Best...

**Comment by Clooney24** [comment]
Hi, 

I had the same question and tried on Neo4j 3.5.5 with
`graphaware-nlp-3.5.4.53.16.jar
graphaware-server-enterprise-all-3.5.4.53.jar
nlp-stanfordnlp-3.5.4.53.17.jar
stanford-german-corenlp-2018-10-05-models.jar `
and
`CALL ga.nlp.config.setDefaultLanguage('de')`.

It first looked like it succeeded, but the part of speech tagging did not work properly. Almost all parts are tagged as Nouns "NN" or "NNS" and some non-verbs as "VBZ". 

I'm not sure if it was my mistake, but these results are not usable for any case.

Best Reiner

Here the results:

```
Hallo	[O]	[NNP]
mein	[O]	[RB]
Name	[O]	[VB]
ist	[O]	[NN]
Max Mustermann	[PERSON]	[NNP]
und	[O]	[NN]
ich	[O]	[NN]
habe	[O]	[NN]
mich	[O]	[NN]
gestern	[O]	[NN]
auf	[O]	[NN]
die	[O]	[VB]
Stelle	[PERSON]	[NNP]
Koch	[PERSON]	[NNP]
Koch	[PERSON]	[NNP]
beworben	[O]	[NN]

Können Sie	[PERSON]	[NNP]
mir	[O]	[NNP]
bitte	[O]	[NN]
mitteilen	[O]	[NN]
ob	[O]	[NN]
ich	[O]	[NN]
Chancen	[O]	[NNP]
habe	[O]	[NN]
genommen	[O]	[NN]
zu	[O]	[NN]
werden	[O]	[NN]

Sie	[O]	[NN]
erreichen	[O]	[NN]
mich	[O]	[NN]
telefonisch	[O]	[NN]
unter	[O]	[VBZ]
000000	[O]	[CD]
oder	[O]	[NN]
per	[O]	[IN]
E-Mail	[O]	[NN]
unter	[O]	[VBZ]
Vielen	[O]	[NNP]
Dank	[O]	[NNP]
```
