### ISSUE TITLE
No procedure with the name `ga.nlp.createSchema` 

### ISSUE THREAD

**Issue by Niharika0727** [graphaware/neo4j-nlp#121]
Are any plugins required separately?

I have installed below plugins:
graphaware-nlp-3.4.6.52.12
graphaware-server-community-all-3.4.6.52
Graphaware-server-enterprise-all-3.4.6.52
nlp-opennlp-3.3.2.52.6
nlp-stanfordnlp-3.4.6.52.12

My neo4j version-3.4.7

 and i Appended the following configuration in the neo4j.conf file in the config/ directory:

 dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware
  com.graphaware.runtime.enabled=true
  com.graphaware.module.NLP.1=com.graphaware.nlp.module.NLPBootstrapper
  dbms.security.procedures.whitelist=ga.nlp.*

When i try to run "CALL ga.nlp.createSchema()"

error: Neo.ClientError.Procedure.ProcedureNotFound: There is no procedure with the name `ga.nlp.createSchema` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.
 
Can you please provide me with the solution?

**Comment by ikwattro** [comment]
HI @Niharika0727 

You need 
graphaware-nlp-3.4.6.52.12
graphaware-server-community-all-3.4.6.52
nlp-stanfordnlp-3.4.6.52.12

That's it. Make sure there are no errors in your logs when starting up, if there are, please post them here.
