### ISSUE TITLE
Java.io.IOException seen when calling ga.nlp.processor.addPipeline with nlp-stanfordnlp-3.4.9.52.15

### ISSUE THREAD

**Issue by chibuagu** [graphaware/neo4j-nlp#127]
I receive an error when I call this procedure as follows: 

CALL ga.nlp.processor.addPipeline({textProcessor: 'com.graphaware.nlp.processor.stanford.StanfordTextProcessor', name: 'customStopWords', processingSteps: {tokenize: true, ner: true, dependency: false}, stopWords: '+,result, all, during', 
threadNumber: 20})

Error message received is: 

Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `ga.nlp.processor.addPipeline`: Caused by: java.io.IOException: Unable to open "edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger" as class path, filename or URL

**Comment by chibuagu** [comment]
I installed the standard core NLP module and I now getting the following error: 

Error: Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure ga.nlp.processor.addPipeline: Caused by: java.lang.RuntimeException: Processor with name 'com.graphaware.nlp.processor.stanford.StanfordTextProcessor' does not exist

**Comment by ikwattro** [comment]
Can you list your plugins directory

**Comment by chibuagu** [comment]
![image](https://user-images.githubusercontent.com/9625383/47217178-87561480-d375-11e8-9d0e-0f470e7a9ee2.png)

**Comment by ikwattro** [comment]
You are missing this plugin : https://products.graphaware.com/download/nlp-stanford-nlp/nlp-stanfordnlp-3.4.9.52.15.jar

**Comment by chibuagu** [comment]
Thanks @ikwattro ,

Now the error message has changed back to what I had originally: 

Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `ga.nlp.processor.addPipeline`: Caused by: java.io.IOException: Unable to open "edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger" as class path, filename or URL

**Comment by ikwattro** [comment]
Sorry, I did not realized. Your stanford-corenlp is not good, you need the one with no kbc in the name : http://nlp.stanford.edu/software/stanford-english-corenlp-2018-10-05-models.jar

Also, specify the language in your pipeline : 

```
CALL ga.nlp.processor.addPipeline({
language: 'en',
textProcessor: 'com.graphaware.nlp.processor.stanford.StanfordTextProcessor', name: 'customStopWords', processingSteps: {tokenize: true, ner: true, dependency: false}, stopWords: '+,result, all, during',
threadNumber: 20})
```

This is pretty new changes, we will make sure to make the documentation clear.

**Comment by chibuagu** [comment]
Great! That worked fine. Thanks @ikwattro
