### ISSUE TITLE
There is no procedure with the name `ga.nlp.config.setDefaultLanguage`

### ISSUE THREAD

**Issue by EvanKnowles** [graphaware/neo4j-nlp#130]
Following the steps in the tutorial [here](https://github.com/graphaware/neo4j-nlp), the `createSchema` call is found correctly but on setting the default language,

    CALL ga.nlp.config.setDefaultLanguage('en')

    Neo.ClientError.Procedure.ProcedureNotFound: There is no procedure with the name `ga.nlp.config.setDefaultLanguage` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.

JARs I have are:

	graphaware-nlp-3.4.9.52.15.jar
	graphaware-server-community-all-3.4.9.52.jar
	nlp-stanfordnlp-3.4.9.52.15.jar
	stanford-english-kbp-corenlp-2018-10-05-models.jar

**Comment by ikwattro** [comment]
Hi @EvanKnowles 

Yes, that procedure was added after the last release, we should make a new release soon.

You can replicate the behavior of that procedure by doing `CALL ga.nlp.config.set('SETTING_fallbackLanguage', 'en') ` in the meantime.
