### ISSUE TITLE
APOC procedures fail after installation of neo4j-nlp

### ISSUE THREAD

**Issue by DouglasLapsley** [graphaware/neo4j-nlp#133]
Neo4j 3.4.7
apoc-3.4.0.3.jar
graphaware-nlp-3.4.7.52.13.jar
graphaware-server-community-all-3.4.7.52.jar
nlp-stanfordnlp-3.4.7.52.13.jar
stanford-english-corenlp-2018-10-05-models.jar

Windows 10 with Neo4j Browser 3.2.13 (downloaded today)

I create a new database, install APOC and it runs fine `(e.g. call apoc.help('keyword')`).  

I then add the graphaware plugins and the required lines to the config file:

  ```
dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware
  com.graphaware.runtime.enabled=true
  com.graphaware.module.NLP.1=com.graphaware.nlp.module.NLPBootstrapper
  dbms.security.procedures.whitelist=ga.nlp.*
```

I start the database again and it loads fine, but I can't run any APOC calls at all:

`Neo.ClientError.Procedure.ProcedureNotFound: There is no procedure with the name `apoc.help` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.`

If I list available procedures I don't have any APOC procedures listed now.

I tried stopping the database and re-installing APOC, but that didn't help.

Any ideas please?

Thanks!

**Comment by ikwattro** [comment]
You need to whitelist apoc procedures as well : 

```
dbms.security.procedures.whitelist=apoc.*,ga.nlp.*
```

**Comment by DouglasLapsley** [comment]
Brilliant thank you!  That worked :)

**Comment by vijji90** [comment]
> apoc.*

Thank You
