### ISSUE TITLE
ERROR processing mime types

### ISSUE THREAD

**Issue by infinitescale** [graphaware/neo4j-nlp#135]
Is this an encoding issue? or does all text need to be in a specific format for relations to work?

ERROR A message body reader for Java class com.graphaware.nlp.enrich.conceptnet5.ConceptNet5EdgeResult, and Java type class com.graphaware.nlp.enrich.conceptnet5.ConceptNet5EdgeResult, and MIME media type text/html; charset=utf-8 was not found

**Comment by ikwattro** [comment]
Can you give more context ? As well as more lines from the stacktrace

**Comment by infinitescale** [comment]
Processing text from articles extracted from the internet - the text is not entirely clean -(output from bs4)

2018-11-19 06:08:04.300+0000 ERROR A message body reader for Java class com.graphaware.nlp.enrich.conceptnet5.ConceptNet5EdgeResult, and Java type class com.graphaware.nlp.enrich.conceptnet5.ConceptNet5EdgeResult, and MIME media type text/html; charset=utf-8 was not found
2018-11-19 06:08:04.300+0000 ERROR The registered message body readers compatible with the MIME media type are:
*/* ->
  com.sun.jersey.core.impl.provider.entity.FormProvider
  com.sun.jersey.core.impl.provider.entity.StringProvider
  com.sun.jersey.core.impl.provider.entity.ByteArrayProvider
  com.sun.jersey.core.impl.provider.entity.FileProvider
  com.sun.jersey.core.impl.provider.entity.InputStreamProvider
  com.sun.jersey.core.impl.provider.entity.DataSourceProvider
  com.sun.jersey.core.impl.provider.entity.XMLJAXBElementProvider$General
  com.sun.jersey.core.impl.provider.entity.ReaderProvider
  com.sun.jersey.core.impl.provider.entity.DocumentProvider
  com.sun.jersey.core.impl.provider.entity.SourceProvider$StreamSourceReader
  com.sun.jersey.core.impl.provider.entity.SourceProvider$SAXSourceReader
  com.sun.jersey.core.impl.provider.entity.SourceProvider$DOMSourceReader
  com.sun.jersey.core.impl.provider.entity.XMLRootElementProvider$General
  com.sun.jersey.core.impl.provider.entity.XMLListElementProvider$General
  com.sun.jersey.core.impl.provider.entity.XMLRootObjectProvider$General
  com.sun.jersey.core.impl.provider.entity.EntityHolderReader

**Comment by ikwattro** [comment]
And what is the procedure call that you used for conceptnet ?

**Comment by infinitescale** [comment]
CALL ga.nlp.enrich.concept
