### ISSUE TITLE
Failed to invoke procedure `ga.nlp.annotate`: Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by sgm0107** [graphaware/neo4j-nlp#140]
Using 3.5.1 Neo4J and using all 3.5.1 Jars for plugins
I am getting the NullPointerException when I call ga.nlp.annotate. I followed the instructions from https://github.com/graphaware/neo4j-nlp 

Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `ga.nlp.annotate`: Caused by: java.lang.NullPointerException

![image](https://user-images.githubusercontent.com/10553503/51288511-6bcccb00-19b1-11e9-91d9-1b2f15ef120d.png)

Please help

**Comment by ikwattro** [comment]
Can you give the full query please

**Comment by sgm0107** [comment]
After spending more time on this problem I realized the real problem was with certain content of the PDF document that I was using. Most of the documents goes through successfully. I guess we can close this issue. Thanks a ton for the response
