### ISSUE TITLE
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `ga.nlp.processor.addPipeline`: Caused by: java.lang.NoSuchMethodError: com.graphaware.nlp.dsl.request.PipelineSpecification.getLanguage()Ljava/lang/String;

### ISSUE THREAD

**Issue by yopooja** [graphaware/neo4j-nlp#141]
![ga_pipeline_2](https://user-images.githubusercontent.com/16745372/52553897-2910de00-2e0b-11e9-9116-9dcc8e198e3e.png)

**Comment by ikwattro** [comment]
Did you download the plugins from https://products.graphaware.com ?

**Comment by yopooja** [comment]
@ikwattro Yes I downloaded from there. Thanks a lot it was version problem of graphawre-nlp-3.4.7.52.13 , when I downloaded graphawre-nlp-3.5.1.53.16.jar it worked.
