### ISSUE TITLE
TextRank Summarization

### ISSUE THREAD

**Issue by randahe** [graphaware/neo4j-nlp#142]
when run this command : MATCH (a:AnnotatedText)
CALL ga.nlp.ml.textRank.summarize({annotatedText: a}) YIELD result
RETURN result
the result was success, but summaryRelevance , summaryRank  properties was  not added to Sentence  nodes

**Comment by vlasta-kus** [comment]
Hi @randahe, which plugins versions and neo4j version do you use? I just tested with 3.4.7 and all works.
Could you also check please neo4j logs (`logs/neo4j.log`) for any messages during execution of the summariser?
Thanks.

**Comment by randahe** [comment]
Thanks for response
I'm using neo4j v 3.4.12 and plugin 3.4.9
when check log file, these warning was realized
2019-03-07 13:25:59.818+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=4309, gcTime=4339, gcCount=1}
2019-03-07 13:26:03.178+0000 WARN [o.n.k.i.c.VmPauseMonitorComponent] Detected VM stop-the-world pause: {pauseTime=2061, gcTime=0, gcCount=0}

**Comment by vlasta-kus** [comment]
I recreated your conditions and can't replicate the issue, all worked well for me. 
Neo4j 3.4.12
`plugins/` directory:
```
Vlastas-MacBook-Pro:neo4j-enterprise-3.4.12 vlasta$ ll plugins/
total 2234656
-rw-r--r--@ 1 vlasta  staff    60639779 Oct 14 21:09 graphaware-nlp-3.4.9.52.15.jar
-rw-r--r--@ 1 vlasta  staff    13982383 Oct 14 17:21 graphaware-server-enterprise-all-3.4.9.52.jar
-rw-r--r--@ 1 vlasta  staff    15571412 Oct 14 22:39 nlp-stanfordnlp-3.4.9.52.15.jar
-rw-r--r--@ 1 vlasta  staff  1038970602 Mar  7 15:56 stanford-english-corenlp-2018-10-05-models.jar
```

`conf/neo4j.conf` contains at the end:
```
dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware
com.graphaware.runtime.enabled=true
com.graphaware.module.NLP.1=com.graphaware.nlp.module.NLPBootstrapper
```

This is the test I ran:
```
call ga.nlp.annotate({text: "The UK's attorney general says Brexit negotiations will continue as EU officials call for acceptable ideas by Friday to break the impasse.
Geoffrey Cox said plans to solve the deadlock over the Irish backstop were \"as clear as day\", with just days until MPs vote on the Brexit deal.
Commons Leader Andrea Leadsom confirmed the vote will be held on 12 March.
Chancellor Philip Hammond has warned Brexiteers to vote for the deal or face delay to the UK's exit from the EU.
The backstop is an insurance policy designed to prevent physical checks on the border between Northern Ireland and the Republic of Ireland.", id: -1, pipeline: "defaultEN"})
YIELD result return result
```

Please make sure your document is not empty, that there are multiple sentences extracted and that they have some attached `Tag` nodes.

If it still doesn't work, please paste:
* content of your `plugins/` dir
* any message from `logs/neo4j.log` (what you pasted is from `debug.log` and that warning is not a problem). To get proper logging functional, please remove slf4j-nop from the `lib/` dir of your neo4j (`rm lib/slf4j-nop-1.7.25.jar`) and put there `slf4j-simple-1.7.7.jar` (https://mvnrepository.com/artifact/org.slf4j/slf4j-simple/1.7.7). 
Hope it helps,
Vlasta

**Comment by ikwattro** [comment]
Also please paste the text you are using so we can replicate correctly.

**Comment by randahe** [comment]
i repeat my experiment after adding slf4j-simple-1.7.7.jar, i get the same thing
actually i run my test in existing database with multiple nodes , i ran this 
![image](https://user-images.githubusercontent.com/32357116/54127947-9f592e00-4413-11e9-915e-d916c0ce79e3.png)
in my database i have 41 requirements but no requirement with empty detail then i ran
![image](https://user-images.githubusercontent.com/32357116/54128107-01199800-4414-11e9-993b-a9afc1d1bea2.png)

inside  logs dir i have nothing except debug.log

**Comment by vlasta-kus** [comment]
It's odd that you have no neo4.log. If you installed from a package, you should have logs somewhere like `/var/log/neo4j/`. My favourite installation method is unpacking tar (zip): https://neo4j.com/download-center/#releases. You then have everything in one dir. 

Anyways, please:
* make sure your annotation produced results (you didn't specify pipeline name, I assume you created one before and set it as default?), i.e. AnnotatedText has Sentence nodes attached and sentence nodes have Tags attached
* paste  content of your `plugins/` directory
* paste one sample text (unless confidential, of course)

**Comment by randahe** [comment]
I already apply the mentioned installation method
In new database , i tried your above example , after run 
![image](https://user-images.githubusercontent.com/32357116/54422599-8accac80-4717-11e9-8781-e1b1ad35dbbc.png)

also summaryRelevance,sunnaryank property was not exist 
here is my plugin content:

![image](https://user-images.githubusercontent.com/32357116/54422402-16920900-4717-11e9-922d-686da85f0ace.png)

**Comment by randahe** [comment]
my goal is to search for a text within the analyzed text and returning the most popular sentences(ranking), can you suggest the suitable commands for this task

**Comment by ikwattro** [comment]
Please send a copy of your graph.db, it seems we cannot reproduce, we would need to inspect the texts you are using.

**Comment by randahe** [comment]
Please find attached a copy of graph.db

**Comment by ikwattro** [comment]
There is nothing attached here, upload it to dropbox or so and paste the link.

**Comment by randahe** [comment]
I attached rar file in mail
