### ISSUE TITLE
Neo.ClientError.Procedure.ProcedureNotFound

### ISSUE THREAD

**Issue by SreenijaK** [graphaware/neo4j-nlp#144]
Neo.ClientError.Procedure.ProcedureNotFound: There is no procedure with the name `ga.nlp.config.set` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.

even though I've added following jars:
graphaware-server-community-all-3.5.2
graphaware-nlp-3.5.2.53.16
nlp-stanfordnlp-3.5.2.53.17
stanford-english-kbp-corenlp-2018-10-05-models

**Comment by ikwattro** [comment]
Post your configuration

**Comment by SreenijaK** [comment]
<img width="520" alt="aa" src="https://user-images.githubusercontent.com/41004864/54588723-c46c2300-4a49-11e9-9392-92edd6f7b943.PNG">

now i get an error when i give the following:

CALL ga.nlp.processor.addPipeline({
language: 'en',
textProcessor: 'com.graphaware.nlp.processor.stanford.StanfordTextProcessor', name: 'customStopWords', processingSteps: {tokenize: true, ner: true, dependency: false}, stopWords: '+,result, all, during',
threadNumber: 20})

Error:
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `ga.nlp.processor.addPipeline`: Caused by: java.lang.NullPointerException

**Comment by ikwattro** [comment]
The model you downloaded is the wrong one, in the README we show you the name of the model you have to download from stanford : `stanford-english-corenlp-2018-10-05-models.jar`

**Comment by SreenijaK** [comment]
![image](https://user-images.githubusercontent.com/41004864/54658985-fcc93b00-4af5-11e9-8240-3b3d2c7f65aa.png)
I've changed the plugin and now i gave the following:
CALL ga.nlp.processor.addPipeline({
name:"transcript",
textProcessor: 'com.graphaware.nlp.processor.stanford.StanfordTextProcessor',
processingSteps: {tokenize:true, ner:true, dependencies:true}
})
-"SUCCESS"
CREATE (news:News {text:"Scores of people were already lying dead or injured inside a crowded Orlando nightclub,
    and the police had spent hours trying to connect with the gunman and end the situation without further violence.
    But when Omar Mateen threatened to set off explosives, the police decided to act, and pushed their way through a
    wall to end the bloody standoff."}) RETURN news;
})

MATCH (n:News)
CALL ga.nlp.annotate({text:n.text, id: n.uuid}) YIELD result
MERGE (n)-[:HAS_ANNOTATED_TEXT]->(result)
RETURN n, result;

it gives the error
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `ga.nlp.annotate`: Caused by: java.lang.RuntimeException: A pipeline should be given or set as default

I still have very less understanding about the pipelines. pls help.

**Comment by tanzirhasan** [comment]
I have similar problem as SreenijaK  is having and have exact same configuration as SreenijaK. Added the  `stanford-english-corenlp-2018-10-05-models.jar`  in plugin folder,but still getting the same error :`Neo.ClientError.Procedure.ProcedureNotFound`

**Comment by ikwattro** [comment]
Make sure that you have whitelisted the procedures : 

```
dbms.security.procedures.whitelist=ga.*
```

And also that there is only one line in your neo4j.conf containing this setting ( a common issue is to have one line for apoc and one line for nlp 

```
dbms.security.procedures.whitelist=ga.*
dbms.security.procedures.whitelist=apoc.*
```

should become 

```
dbms.security.procedures.whitelist=ga.*,apoc.*
```

**Comment by tanzirhasan** [comment]
Adding `dbms.security.procedures.whitelist=ga.*,apoc.*` as single line in the config file did the trick, earlier they were in separate lines. 
Thanks @ikwattro

**Comment by saidireddyM** [comment]
Hello Team,

I got an error(below mentioned)  while creating a model in Neo4j 
I added all three plugins like Apoc, Graph Algorthims, GraphQL
And i added ml model jar file(neo4j-ml-models-1.0.3) in plugins.

Can you please check and provide me the feasible solution.

**Neo.ClientError.Procedure.ProcedureNotFound
There is no procedure with the name `regression.linear.create` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.**

Thanks
Saidireddy
