### ISSUE TITLE
LDA topic modeling 

### ISSUE THREAD

**Issue by randahe** [graphaware/neo4j-nlp#146]
Neo.ClientError.Procedure.ProcedureNotFound: There is no procedure with the name `ga.nlp.ml.enterprise.lda.compute` registered for this database instance

I install  enterprise Neo4j  3.4.12 trial version with 3.4.9 graphaware-nlp, nlp-stanfordnlp and graphaware-server-enterprise  plugin

**Comment by ikwattro** [comment]
This is an NLP Enterprise procedure, only accessible to our customers or during some trainings.
