### ISSUE TITLE
Error: Service Unavailable after calling `ga.nlp.enrich.concept`

### ISSUE THREAD

**Issue by walu2** [graphaware/neo4j-nlp#149]
Hello guys,

It is my first post here. 
Foremost big kudos guys 👏 for an excellent piece of code 👍 

Anyway when I try to run the following command on my graph schema:
`MATCH (n:Tag)
CALL ga.nlp.enrich.concept({enricher: 'conceptnet5', tag: n, depth:1, admittedRelationships:["IsA","PartOf"]})
YIELD result
RETURN result` 

I'm receiving following very vague error (_of note - managed via Neo4j Desktop, not any browser_):
`ServiceUnavailable: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being unavailable, using the wrong connection URL or temporary network problems. If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket \`readyState\` is: 3`

Did I miss something in config? Surely all initial steps has been done based on README file.

Any thoughts why does it happen?

Thanks in advance

**Comment by davidmeza1** [comment]
This may help, https://neo4j.com/developer/kb/explanation-of-error-websocket-connection-failure/

**Comment by walu2** [comment]
Hi,

thanks for an answer. 

Unfortunately, inspite of the fact that I uncommented line `dbms.connector.bolt.address=0.0.0.0:7687` in my `neo4j.conf` error still occurs, no luck 😢

**Comment by ikwattro** [comment]
Hi @walu2 , the errors you are receiving are not part of our plugin. They are basically errors of the neo4j browser.

Secondly, we do not recommend to use the nlp stack in a Neo4j desktop environment, NLP requires some CPU/Memory to perform correctly, and as Neo4j Desktop is embedded in an electron application, this causes some issues.
