### ISSUE TITLE
Question - latest version of plugin and neo4j 3.5.7

### ISSUE THREAD

**Issue by mfkilgore** [graphaware/neo4j-nlp#150]
I am tracking down a potential issue with apoc.periodic.iterate which occurs in my environment running your nlp plugin.  I would like to test against the latest 3.5.7 release, will the latest nlp plugins work with that release?

**Comment by shreyas219** [comment]
Hi,
You need to whitelist the apoc procedures as well along with ga.nlp. 
Try the following line in neo4j configuration file:
dbms.security.procedures.whitelist=ga.nlp.*,apoc.*

I hope this helps you.
