### ISSUE TITLE
Unable to add word2vec models

### ISSUE THREAD

**Issue by meefen** [graphaware/neo4j-nlp#153]
Hi there,

I tried to add a word2vec model following the README file of this repo but `CALL ga.nlp.ml.word2vec.listModels` returned no records. Below are things I did:

First, I downloaded the `numberbatch-en-19.08.txt.gz` file from the [NumberBatch repo](https://github.com/commonsense/conceptnet-numberbatch). I unzipped the file and put it in a file folder.

Second, I ran the following code in Neo4j browser to add the model. Neo4j returned "SUCCESS".

```
CALL ga.nlp.ml.word2vec.addModel(
   "/Users/user/Documents/src/neo4j/neo4j-nlp/numberbatch-en-19.08",
   "/Users/user/Documents/src/neo4j/neo4j-nlp/word2vec_idx",
   "en-numberbatch"
)
```

However, when I ran `CALL ga.nlp.ml.word2vec.listModels`, Neo4j returned no records. When I tried to compute the cosine similarity between two words, it returned 0.

Anything I did wrong? Does the folder where I put the model matter? Does adding `.txt` matter? 

Thank you in advance!

**Comment by ikwattro** [comment]
Hi @meefen , Are the paths provided directories ? 

The procedure you tried seems similar to a working procedure described here https://github.com/graphaware/neo4j-nlp/issues/52

**Comment by meefen** [comment]
@ikwattro the first two parameters are .txt files. I tried to add `.txt` as well. This might be where the problem is. Please advise!

Yes, I actually followed the procedure you posted there. 

Thank you!
