### ISSUE TITLE
Compatibility with Spanish Text Data

### ISSUE THREAD

**Issue by ghost** [graphaware/neo4j-nlp#158]
Hi,

I am trying to use GA-NLP to processes text in spanish, however when I try to create the pipeline in order to  add a custom text processor :

`CALL ga.nlp.processor.addPipeline({ language: 'es',  etc...))
`
The next error rise:

> Failed to invoke procedure `ga.nlp.processor.addPipeline`: Caused by: java.lang.RuntimeException: Multiple languages not supported in this version

The readme file in the GitHub repository establish that the next command must be executed in order to specify the language: 

`CALL ga.nlp.config.setDefaultLanguage('en')
`
We already try to change the parameter 'en' for 'es' or 'spanish' and it doesn't seem to work because the procedure

`ga.nlp.processor.addPipeline()
`
is still creating a Pipeline in english by default. There is more, when I try to set the language the exception mentioned in the first error mentioned arise.

We also try, unsuccessfully, to find in the java code the answer but it seems that the only languages supported are english and german. 

Finally, maybe we need the enterprise plugin .jar file in order to use the spanish language configuration, but we don't really know. 

I hope that anybody can help us with this problem, thanks!

**Comment by ikwattro** [comment]
Hi,

We currently do not support Spanish as part of the open source version. Yes only English and German are supported, altho adding Spanish is a matter of adding the language and adding the dependency in the stanford package to the Spanish models provided by Stanford.
