### ISSUE TITLE
Failed to invoke procedure `ga.nlp.annotate`: Caused by: java.lang.RuntimeException: No pipeline null

### ISSUE THREAD

**Issue by sudeepdestiny** [graphaware/neo4j-nlp#159]
Using 3.5.14 Neo4J and using all 3.5.14 Jars for plugins
I am getting the NullPointerException when I call ga.nlp.annotate. I followed the instructions from https://github.com/graphaware/neo4j-nlp

```
MATCH (n:News)
CALL ga.nlp.annotate({text: n.text, id: id(n)})
YIELD result
MERGE (n)-[:HAS_ANNOTATED_TEXT]->(result)
RETURN result
```
Error:Failed to invoke procedure `ga.nlp.annotate`: Caused by: java.lang.RuntimeException: No pipeline null

[security.log](https://github.com/graphaware/neo4j-nlp/files/4323427/security.log)
[neo4j.log](https://github.com/graphaware/neo4j-nlp/files/4323429/neo4j.log)
[debug.log](https://github.com/graphaware/neo4j-nlp/files/4323430/debug.log)
![image](https://user-images.githubusercontent.com/12708378/76508670-bcdb3080-6489-11ea-8f1e-5c28a97d31ab.png)

**Comment by nh83012001** [comment]
Mine was resolved by adding the pipeline in. The default pipeline wasn't working. Hope this helps!

MATCH (n:News)
CALL ga.nlp.annotate({text: n.text, id: id(n), pipeline: 'my-pipeline-name'})
YIELD result
MERGE (n)-[:HAS_ANNOTATED_TEXT]->(result)
RETURN result
