### ISSUE TITLE
Installation guide is misleading

### ISSUE THREAD

**Issue by Constantin07** [graphaware/neo4j-nlp#24]
The installation [guide](https://github.com/graphaware/neo4j-nlp) mentions to download `neo4j-nlp` and `neo4j-nlp-stanfordnlp` (or `neo4j-nlp-stanfordnlp`) from https://products.graphaware.com/ but they are not avalable there ... which is confusing.

Also the  `neo4j-framework` probably refers to `framework-server-community` but I'm not sure.

Can the installation instruction be updated on how to install the graphaware plugin ?

Regards,
Constantin

**Comment by moxious** [comment]
As I was getting started I'm creating this: https://github.com/graphaware/neo4j-nlp/pull/30 which addresses some of your points.   On your first point, I checked products.graphaware.com and I was able to find both of those modules easily, so I didn't update anything there.   (I don't work for GraphAware, I'm just a drive-by who had similar issues)

**Comment by Constantin07** [comment]
@moxious thanks for looking into it. Now I can see as well the modules on products.graphaware.com.
I think it was addressed by someone.
