### ISSUE TITLE
No procedure registered for this database

### ISSUE THREAD

**Issue by ManojPrasanth** [graphaware/neo4j-nlp#27]
Any plugins required separately for cosine and for other procedures?

I have installed below plugins:
graphaware-nlp-3.1.3.1.jar
graphaware-server-community-all-3.2.5.51.jar
nlp-opennlp-3.1.3.1.jar

version-3.2.7

but am able to run annotation procedures but not the below procedures:

ga.nlp.language:
There is no procedure with the name ga.nlp.language registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.
ga.nlp.ml.cosine.compute:
There is no procedure with the name ga.nlp.ml.cosine.compute registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.

Please let me know regarding the same.

**Comment by ikwattro** [comment]
Thanks @ManojPrasanth 

Can you please download the right version for the framework here : 

https://products.graphaware.com/

Regarding your issue, it seems our doc is a bit outdated.

The right procedure call for computing cosine similarity is : 

`ga.nlp.ml.similarity.cosine`

and the languageProcedure is `ga.nlp.detectLanguage`

I will make sure to update the doc in the next commit.

Thanks

**Comment by ManojPrasanth** [comment]
Since am not able bring output for below procedures , Can you please give me an example for these in cypher codes , so that i can use in localhost:7474/browser
`ga.nlp.ml.similarity.cosine`
`ga.nlp.detectLanguage`

And if there is a complete module with examples for all procedure , can you give me that link.
If not , please try to make it out since its a new technology and going to be used by many in future , a procedure manual is must with examples.

**Comment by ManojPrasanth** [comment]
Hi ikwattro,

I missed one statement in above comment.
I tried with the newer community version 3.3.0 and plugins are all of same versions.
but still am facing same issue:
ga.nlp.language:
`There is no procedure with the name ga.nlp.language registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.`
ga.nlp.ml.cosine.compute:
`There is no procedure with the name ga.nlp.ml.cosine.compute registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.`

```
ga.nlp.ml.similarity.cosine
ga.nlp.detectLanguage
```

Please give me an example for above

Thanks

**Comment by ikwattro** [comment]
Fixed
