### ISSUE TITLE
No Procedure with ga.nlp.search registered for this database instance. 

### ISSUE THREAD

**Issue by rajeev830** [graphaware/neo4j-nlp#48]
If I call the following procedure, CALL ga.nlp.search("Chatbot") YIELD result, score
MATCH (result)<-[]-(news:News)
RETURN DISTINCT news, score
ORDER BY score desc;
I get the error "There is no procedure with the name `ga.nlp.search` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed." Am I missing anything?

I have installed the following plugins for neo4j-
graphaware-nlp-3.3.1.51.2
graphaware-server-community-all-3.3.1.51
nlp-stanfordnlp-3.3.1.51.2
graphaware-neo4j-to-elasticsearch-3.3.1.51.7

**Comment by ikwattro** [comment]
Hi @rajeev830 

Yes the procedure has not been ported after the refactoring. We plan to do it. However you can see the Cypher query for reproducing the search procedure here : 

https://github.com/graphaware/neo4j-nlp/blob/master/src/main/java/com/graphaware/nlp/application/search/SearchProcedure.java#L48

**Comment by rajeev830** [comment]
Thanks @ikwattro.

**Comment by SreenijaK** [comment]
@ikwattro @rajeev830  i'm still not able to use ga.nlp.search. can you please help me on how i can proceed for search.
Thankyou.
