### ISSUE TITLE
Application thread is blocked 

### ISSUE THREAD

**Issue by good-marketing** [graphaware/neo4j-nlp#49]
Hi, 

I am not sure this is a neo4j-nlp related but I have the following problem.

I need to run sentiment analysis on a large number of texts (2.5mil). I am testing how to approach it, so far I've come up with

``// NLP iterate sentiment
call apoc.periodic.iterate(
"MATCH (a:AnnotatedText) WHERE size(labels(a)) = 1 RETURN a LIMIT 10000",
"CALL ga.nlp.sentiment(a) YIELD result RETURN result;"
,{batchSize: 1000, iterateList: false})
``

This approach works for a while, but when I check the logs I get a warning messages like '
2018-01-22 12:53:00.371+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 14301ms.` 

What could I do to improve performance and get rid of these messages. I am using neo4j 3.3 enterprise and the latest version of the plugin (for apoc and nlp framework). 

Thanks.

**Comment by ikwattro** [comment]
Those are GC logs, quite normal in such lifecycle. However we improved the performance quite a bit and there should be much much less logs like this. See last comment in #64
