### ISSUE TITLE
Skipping words with å ä ö

### ISSUE THREAD

**Issue by AndreasHenningsson** [graphaware/neo4j-nlp#51]
Errordescription
------------------
When using ga.nlp.annotate checkLanguage:false on a text containing Words with å ä ö, annotate skips the entire words.
Example of text in a node
"Det är idag kallt. Året är 2018"

The Words "är" and "året" seems to be skipped by the annotate funktions as Nodes "Tag" and "TagOccurence"

Installed base
---------------
Installed package on a Neo 3.3.1:
 graphaware-nlp-3.3.1.51.2
 nlp-opennlp-3.3.1.51.2
 nlp-stanfordnlp-3.3.1.51.2
 graphaware-server-community-all-3.3.1.51

Used comand:
----------------
MATCH (n:Dokument) CALL ga.nlp.annotate({text: n.text, id: id(n), checkLanguage: false}) YIELD result MERGE (n)-[:HAS_ANNOTATED_TEXT]->(result) RETURN result

**Comment by ikwattro** [comment]
Thanks for reporting @AndreasHenningsson . Fixed in master.

**Comment by ikwattro** [comment]
@AndreasHenningsson 

The release 3.3.2.51.4 contains the fix for this. You can download it from https://products.graphaware.com
