### ISSUE TITLE
ga.nlp.ml.word2vec.attach gives  java.lang.RuntimeException: Error

### ISSUE THREAD

**Issue by AndreasHenningsson** [graphaware/neo4j-nlp#52]
When using the following commando match (n:Tag) call ga.nlp.ml.word2vec.attach(n) YIELD result return result

It gives 
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `ga.nlp.ml.word2vec.attach`: Caused by: java.lang.RuntimeException: Error

Installed base
---------------
Neo 3.3.1
 graphaware-nlp-3.3.1.51.2
 nlp-opennlp-3.3.1.51.2
 nlp-stanfordnlp-3.3.1.51.2
 graphaware-server-community-all-3.3.1.51

**Comment by ikwattro** [comment]
Hi @AndreasHenningsson 

I think this process should be better documented. The `attach` method is meant to add the vector of a word to the corresponding node. For that, an existing vectors model should exist.

We recommend ( and tested ) ConceptNet Numberbatch (Word2Vec) : https://github.com/commonsense/conceptnet-numberbatch

I extract the Swedish vectors, you can download it here : 

https://www.dropbox.com/s/co43akx8loidrww/swedishSource.zip?dl=0

How does it work ?

Extract the zip in your import directory of neo4j. 
This will serve as the source, next the vectors should be added in a lucene index outside of neo4j.

The following procedure will do exactly that where you provide the source and destination location : 

```
CALL ga.nlp.ml.word2vec.addModel(
   "/Users/ikwattro/dev/_graphs/nlp/import/swedishSource",
   "/Users/ikwattro/dev/_graphs/nlp/import/swedishIndex",
   "swedish-numberbatch"
)
```
( note that you need to provide the full path )

This should run relatively fast.

You can then return the vectors or for example compute the similarity between two words based on this model : 

```
WITH 
ga.nlp.ml.word2vec.wordVector('äpple', 'swedish-numberbatch') AS appleVector,
ga.nlp.ml.word2vec.wordVector('frukt', 'swedish-numberbatch') AS fruitVector
RETURN ga.nlp.ml.similarity.cosine(appleVector, fruitVector) AS simil

╒══════════════════╕
│"simil"           │
╞══════════════════╡
│0.5729867131088588│
└──────────────────┘
```

**Comment by AndreasHenningsson** [comment]
Many many thanks!
Works like a sharm 😊

Skickades från E-post för Windows 10

Från: Christophe Willemsen
Skickat: den 28 januari 2018 20:27
Till: graphaware/neo4j-nlp
Kopia: AndreasHenningsson; Mention
Ämne: Re: [graphaware/neo4j-nlp] ga.nlp.ml.word2vec.attach givesjava.lang.RuntimeException: Error (#52)

Hi @AndreasHenningsson
I think this process should be better documented. The attach method is meant to add the vector of a word to the corresponding node. For that, an existing vectors model should exist.
We recommend ( and tested ) ConceptNet Numberbatch (Word2Vec) : https://github.com/commonsense/conceptnet-numberbatch
I extract the Swedish vectors, you can download it here :
https://www.dropbox.com/s/co43akx8loidrww/swedishSource.zip?dl=0
How does it work ?
Extract the zip in your import directory of neo4j.
This will serve as the source, next the vectors should be added in a lucene index outside of neo4j.
The following procedure will do exactly that where you provide the source and destination location :
CALL ga.nlp.ml.word2vec.addModel(
   "/Users/ikwattro/dev/_graphs/nlp/import/swedishSource",
   "/Users/ikwattro/dev/_graphs/nlp/import/swedishIndex",
   "swedish-numberbatch"
)
( note that you need to provide the full path )
This should run relatively fast.
You can then return the vectors or for example compute the similarity between two words based on this model :
WITH 
ga.nlp.ml.word2vec.wordVector('äpple', 'swedish-numberbatch') AS appleVector,
ga.nlp.ml.word2vec.wordVector('frukt', 'swedish-numberbatch') AS fruitVector
RETURN ga.nlp.ml.similarity.cosine(appleVector, fruitVector) AS simil

╒══════════════════╕
│"simil"           │
╞══════════════════╡
│0.5729867131088588│
└──────────────────┘

**Comment by ikwattro** [comment]
Closing this issue as the documentation has been updated.
