### ISSUE TITLE
textprocessor dosent seem to care about stopword

### ISSUE THREAD

**Issue by AndreasHenningsson** [graphaware/neo4j-nlp#53]
Step1:
CALL ga.nlp.processor.addPipeline ({textProcessor: 'com.graphaware.nlp.processor.stanford.StanfordTextProcessor', name: 'customStopwords', stopWords: '+,själv, dig, från, vilkas, dem, ett, varit, varför, att, era, som, dess, skulle, våra, på, sådana, har, blivit, det, vad, eller, sin, efter, i, varje, sådan, de, ditt, han, dessa, vi, med, då, den, mig, denna, ingen, under, henne, sådant, du, hade, vilken, till, över, vår, är, jag, nu, sedan, hans, vid, vara, hur, min, här, sitta, än, ju, blev, ut, bli, sina, hennes, detta, oss, alla, någon, allt, utan, blir, några, åt, vårt, där, samma, inte, inom, hon, något, upp, honom, var, sig, vilket, vart, er, och, kunde, ej, vars, mot, men, ni, ha, din, ert, för, mina, vilka, så, kan, vem, man, en, icke, mitt, när, mycket, deras, mellan, om, dina, av', threadNumber: 20})

Step 2
MATCH (n:Problem)
CALL ga.nlp.annotate({text: n.text, id: id(n)})
YIELD result
MERGE (n)-[:HAS_ANNOTATED_TEXT]->(result)
RETURN result

The above annotation still processes the above listed stopwords.
For example there are Tag that contains the value "dig"

**Comment by ikwattro** [comment]
@AndreasHenningsson It was a regression with the new pipeline loading mechanism. It is fixed into Stanford master ( still has to be ported to Opennlp )

You can download the updated version of the stanford plugin here until the next release : https://www.dropbox.com/s/gi4te8s2ndfbn6p/nlp-stanfordnlp-3.3.2.51.6-SNAPSHOT.jar?dl=0
