### ISSUE TITLE
ConceptNet5 takes forever

### ISSUE THREAD

**Issue by AndreasHenningsson** [graphaware/neo4j-nlp#54]
I not sure if this an error or if should be this way but when I run the below command
CALL ga.nlp.enrich.concept({enricher: 'conceptnet5', tag: n, depth:2, admittedRelationships:["IsA","PartOf"]})

it takes forever to compleate >5 hours (i have never waited than this). There are quite a lot of tags (data comes from a book) but it is not a huge amout a words (from my prespective)

regards 
andreas

**Comment by ikwattro** [comment]
@AndreasHenningsson 

5 hours is way too long.

Can you share the output of the `:schema` command in the browser please.

**Comment by AndreasHenningsson** [comment]
Will do first thing when i’m back in office (friday)

tis 30 jan. 2018 kl. 21:13 skrev Christophe Willemsen <
notifications@github.com>:

**Comment by AndreasHenningsson** [comment]
I run the following commands from python
        graphdb.data("CREATE CONSTRAINT ON (n:Incident) ASSERT n.`Incident Number` IS UNIQUE;")
        graphdb.data("CREATE CONSTRAINT ON (n:Problem) ASSERT n.text IS UNIQUE;")
        graphdb.data("CREATE CONSTRAINT ON (n:Solution) ASSERT n.text IS UNIQUE;")
        graphdb.data("CREATE CONSTRAINT ON (n:AnnotatedText) ASSERT n.id IS UNIQUE;")
        graphdb.data("CREATE CONSTRAINT ON (n:Tag) ASSERT n.id IS UNIQUE;")
        graphdb.data("CREATE CONSTRAINT ON (n:Sentence) ASSERT n.id IS UNIQUE;")
        graphdb.data("CREATE CONSTRAINT ON (n:AnnotatedText) ASSERT n.id IS UNIQUE;")
        graphdb.data("CREATE INDEX ON :Tag(value);") 

The schema looks like this:
Indexes
   ON :Tag(value) ONLINE 
   ON :AnnotatedText(id) ONLINE  (for uniqueness constraint)
   ON :Incident(Incident Number) ONLINE  (for uniqueness constraint)
   ON :Problem(text) ONLINE  (for uniqueness constraint)
   ON :Sentence(id) ONLINE  (for uniqueness constraint)
   ON :Solution(text) ONLINE  (for uniqueness constraint)
   ON :Tag(id) ONLINE  (for uniqueness constraint)

Constraints
   ON ( annotatedtext:AnnotatedText ) ASSERT annotatedtext.id IS UNIQUE
   ON ( incident:Incident ) ASSERT incident.Incident Number IS UNIQUE
   ON ( problem:Problem ) ASSERT problem.text IS UNIQUE
   ON ( sentence:Sentence ) ASSERT sentence.id IS UNIQUE
   ON ( solution:Solution ) ASSERT solution.text IS UNIQUE
   ON ( tag:Tag ) ASSERT tag.id IS UNIQUE

I Think I see the problem. The tag with attribute is not indexed. Hmmm

@ikwattro

**Comment by ikwattro** [comment]
It does lookups on :Tag(id) so it seems your schema is correct. How many tags are you trying to do at once ?

**Comment by AndreasHenningsson** [comment]
@ikwattro No More than 27800 Tags

**Comment by ikwattro** [comment]
@AndreasHenningsson 

I forgot something about the concept net public api, it is rate limited to 6000 request per hour (which for you with 27k tags returning maybe 20 results and then depth 2 will potentially takes days). This is why we roll our own instance, thankfully they made it super easy with docker : 

https://github.com/commonsense/conceptnet5/wiki/Running-your-own-copy#running-conceptnet-using-docker

You will have to modify the limit variables here : 

https://github.com/commonsense/conceptnet-web/search?utf8=%E2%9C%93&q=6000&type=

Then you can tell the NLP plugin the new url for your own conceptnet api : 

```
CALL ga.nlp.config.set('SETTING_CONCEPT_NET_5_URL', 'myserver:8080')
```

**Comment by AndreasHenningsson** [comment]
@ikwattro Thanks, a docker is set up

BUT, is this the same issue when Annotating text. It takes 5170 seconds to annotate 7050 Words. Diveded in 19 documents.

It is not the server capacity that is the limit (4 cpu, dedicated 19 G RAM)

**Comment by ikwattro** [comment]
@AndreasHenningsson is it on the same data as #58 ?

**Comment by AndreasHenningsson** [comment]
@ikwattro yes

**Comment by ikwattro** [comment]
ok I will test that tonight.

**Comment by ikwattro** [comment]
So, it took me approx 2h30 for the fully annotated db. (7k tags approx).

Request rate against the conceptnet server : 13.64 req/s
Total rels created : 26814
Total tags after: 16890

This is the query used : 

```
CALL apoc.periodic.iterate('MATCH (n:Tag) RETURN n', '
CALL ga.nlp.enrich.concept({enricher: "conceptnet5", tag: n, depth:2, admittedRelationships:["IsA","PartOf"], checkLanguage:false})
YIELD result SET n:ConceptProcessed RETURN count(*)',{batchSize:100, iterateList:false})
```

Would it be possible to have some log outputs from the conceptnet server you used ?
