### ISSUE TITLE
Failed to invoke procedure `ga.nlp.ml.similarity.cosine`: Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Missing key 'input'

### ISSUE THREAD

**Issue by jlondrejcka** [graphaware/neo4j-nlp#59]
Howdy!

I am using graphaware-nlp-3.32

Error:

> Failed to invoke procedure `ga.nlp.ml.similarity.cosine`: Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Missing key 'input'

Code:
`MATCH (at:AnnotatedText) 
CALL ga.nlp.ml.similarity.cosine({node:at}) 
YIELD result 
RETURN result`

any and all help is much appreciated!

**Comment by alenegro81** [comment]
Hi,
try in this way:
MATCH (at:AnnotatedText) CALL ga.nlp.ml.similarity.cosine({input:[at]}) YIELD result RETURN result

In this procedure you need specify the list of input. With this query you'll compute similarty between all annotated text. Much better than to use this:

MATCH (at:AnnotatedText) CALL ga.nlp.ml.similarity.cosine({}) YIELD result RETURN result


Let us know,
Alessandro

**Comment by jlondrejcka** [comment]
figured it out:

`MATCH (at:AnnotatedText) with collect(at) as list
CALL ga.nlp.ml.similarity.cosine({input:list, query: null, relationshipType: 'SIMULARITY'}) 
YIELD result 
RETURN result`
