### ISSUE TITLE
Stanford NLP gem constantly running out of memory

### ISSUE THREAD

**Issue by stevecreedon** [graphaware/neo4j-nlp#64]
I am trying to annotate user complaints using the Stanford tokenizerAndDependency pipeline:

     MATCH(n:Complaint)` WHERE NOT (n)-[]->()
     WITH n LIMIT 10
     CALL ga.nlp.annotate({text:n.content, id: id(n), pipeline:'tokenizerAndDependency'}) YIELD result
     MERGE (n)-[:HAS_ANNOTATED_TEXT]->(result)
     RETURN n, result;

But it is glacially slow and despite allocating 10Gb for the heap usually runs out of heap space having processed one or two documents at the most. Typically documents are no more than 400 words long (frequently less) however they are often quite colloquial with less than perfect grammar, especially capitalisation. This happens for both the Stanford NLP tokeniser and tokeniserAndDependency pipeline. If I use the `nlp-opennlp` pipeline it all works fine and pretty quickly.

I can't really share a typical document in a public forum as we have restrictions on sharing information however I could send you one or two examples if needed.

It's so slow I'm sure I must be doing something very wrong.

I'm running neo4j 3.3.2 on an AWS m5.xlarge (2 cores 16Gb Ram) with the following configuration.

     com.graphaware.runtime.stats.disabled=true
     com.graphaware.server.stats.disabled=true
     dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware
     com.graphaware.runtime.enabled=true
     com.graphaware.module.NLP.1=com.graphaware.nlp.module.NLPBootstrapper
     dbms.security.procedures.whitelist=ga.nlp.*
     dbms.memory.heap.initial_size=8G
     dbms.memory.heap.max_size=10G`

The only gems in my plugins dir are:

    graphaware-nlp-3.3.2.52.6.jar  
    graphaware-server-enterprise-all-3.3.2.52.jar
    nlp-stanfordnlp-3.3.2.52.6.jar

These are the indexes:

    INDEX ON :Tag(value)
    INDEX ON :AnnotatedText(id)
    INDEX ON :Complaint(id)
    INDEX ON :Sentence(id)
    INDEX ON :Tag(id)

**Comment by alenegro81** [comment]
Could you share some sample data?

**Comment by ikwattro** [comment]
Hi @stevecreedon For sharing data with us, you can use the following email : 

nlp@graphaware.com

Note that in general ( stanford performance recommendations ) , annotations per paragraphs is recommended, I would try to keep the text to be annotated to approx 50 words.

On another note, I would reduce the LIMIT in your query to 1, you would not notice any differences compared to two, but the transaction will be quite huge with 4000 words graph + occurrences + dependencies.

We are working however on improving this processing, making our own batch annotator that would be best suited, there is already a branch but we cannot commit now to a date of release for this.

Cheers

Christophe

**Comment by fotisz** [comment]
I am experiencing the same issue - the batching process seems to be failing when the graph is more than 15K nodes (avg 20 words/node) even on a 70 GB RAM machine - server just collapses ...

**Comment by ikwattro** [comment]
What are the indexes and constraints in your database @fotisz @stevecreedon ?

**Comment by fotisz** [comment]
CREATE CONSTRAINT ON (n:AnnotatedText) ASSERT n.id IS UNIQUE;
CREATE CONSTRAINT ON (n:Tag) ASSERT n.id IS UNIQUE;
CREATE CONSTRAINT ON (n:Sentence) ASSERT n.id IS UNIQUE;

CREATE INDEX ON :Tag(value);

**Comment by stevecreedon** [comment]
Mine are the same, exactly as per the documentation plus one for my 'Complaint' node.

**Comment by stevecreedon** [comment]
Certainly the text I'm annotating is frequently more than 50 words. I guess I assumed that one 'Complaint' can only have one AnnotatedText node but am I able to split the complaint into smaller text chunks (of less than 50 words) so that a Complaint will have many AnnotatedText nodes ?

**Comment by stevecreedon** [comment]
@ikwattro I have tried limit 1, limit 10, limit 100 - you name it :)

**Comment by ikwattro** [comment]
@fotisz Can you send us the text that triggers the OOM.

**Comment by fotisz** [comment]
@ikwattro can you please confirm if the id of the test is the same as the # appearing on '.... end storing annotated Text 69497'?

**Comment by fotisz** [comment]
``
[debug.log](https://github.com/graphaware/neo4j-nlp/files/1811373/debug.log)

Please see attached

**Comment by ikwattro** [comment]
@fotisz We need the text you are trying to annotate >> nlp@graphaware.com

**Comment by fotisz** [comment]
ok, I run a few performance tests on ga.annotation and it seems that length(n.Text) <= 2500 for the annotation to not run out of memory ... I also did some text cleansing in Java just to be on the safe side (I could share the code if you'd like to have a look) - Would that be something you have come across before?

**Comment by ikwattro** [comment]
We try to keep texts at the size of a paragraph. But we will try to do some benchmarks and come up with a proper recommendation and fix if there is something to fix on our side. The plugins are dependent of the implementations, either Stanford or OpenNLP. https://stanfordnlp.github.io/CoreNLP/memory-time.html

**Comment by fotisz** [comment]
yes I also think this is the common pattern there as I am always getting out of memory issues on specific nodes but there isn't really much coming up on the debug log ... I found the following in the link you provided which might validate my assumption: 

''The slowest annotators are coreference and parsing. Many coreference methods are especially sensitive to the total document length, since they are quadratic or cubic in the number of mentions in the document. The parsing annotators, particularly dynamic-programming constituency parsing, is especially **sensitive to maximum sentence length**. Your processing will be much faster if you either **leave out these annotators or choose options that make them as fast as possible**.''

**Comment by stevecreedon** [comment]
I'm using:

graphaware-nlp-3.3.2.52.6.jar
graphaware-server-enterprise-all-3.3.3.52.jar
nlp-stanfordnlp-3.3.2.52.6.jar

and I can confirm that performance is much improved. Mostly the memory bloat has gone and the annotate process runs quite happily within 2Gb on my Mac. Before it was very frequently chewing up all 13Gb of RAM on an EC2 server.

I have annotated 19000 consumer complaints and am 40% the way through unsupervised keyword extraction. The keywords extracted thus far look far superior to any other techniques we've tried.

**Comment by ikwattro** [comment]
@stevecreedon 

That's very nice to hear !

I am not sure the last improvement of TextRank post-process is in the latest release, so please run this query once all the keywords are extracted, this should remove some non-useful keywords we could identify

```
CREATE INDEX ON :Keyword(numTerms)
```

```
MATCH (n:Keyword) WHERE n.numTerms = 1
WITH n WHERE true
MATCH (t:Tag {id: n.id})
USING INDEX t:Tag(id)
WHERE ANY(x IN t.pos WHERE x STARTS WITH "VB" OR x IN ["JJ","JJS", "JJR","RB","RBR","RBS","RP","WR","IN","WP"])
DETACH DELETE n
```

**Comment by fotisz** [comment]
That's great news ... I am trying the fix out as we speak - what happens when we are working in the millions scale? would that need to go through APOC?

**Comment by ikwattro** [comment]
You can use APOC for iterating over the dataset and run the annotation

The important bit is keeping batchSize to 1 and iterateList false, example : 

```
CALL apoc.periodic.iterate('MATCH (n:Lesson)
WHERE NOT (n)-[:HAS_ANNOTATED_TEXT]->() RETURN n',
'
CALL ga.nlp.annotate({text: n.text, id:id(n), pipeline:"nasa"})
YIELD result
MERGE (n)-[:HAS_ANNOTATED_TEXT]->(result)
',{batchSize:1, iterateList:false})
```

**Comment by ikwattro** [comment]
I'm closing this issue as it has been fixed and there was a new release since then
