### ISSUE TITLE
Procedure not found....

### ISSUE THREAD

**Issue by Vishnubala95** [graphaware/neo4j-nlp#68]
Hi, Kindly help me on this

getting error on running nlp.annotate procedure in Neo4j community edition 

![screenshot from 2018-03-22 17-05-18](https://user-images.githubusercontent.com/36667048/37768441-a4d6bdac-2df3-11e8-8c58-9786b362b56e.png)

**Comment by ikwattro** [comment]
Please post questions that are not issues on StackOverflow or the neo4j-slack channels.
