### ISSUE TITLE
Keyword extraction

### ISSUE THREAD

**Issue by antonioaltamura** [graphaware/neo4j-nlp#90]
I don't get how the keyword exaction works

```
MATCH (a:Paper)
CALL ga.nlp.ml.textRank({annotatedText: a})
YIELD result RETURN result
```
returns a field `return` which is an array of strings "SUCCESS"  

Where can I define the text to be analyzed for the keyword extraction?

**Comment by ikwattro** [comment]
HI @antonioaltamura The text should be annotated before. So you should pass the annotated Text instead, your query should look like this : 

```
MATCH (p:Paper)-[:HAS_ANNOTATED_TEXT]->(a)
CALL ga.nlp.ml.textRank({annotatedText: a})
YIELD result RETURN result
```
